# Generated by Django 5.2.4 on 2026-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("open", "Открыт"), ("closed", "Закрыт")],
                default="open",
                max_length=6,
                verbose_name="status",
            ),
        ),
    ]
